# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: xenial
      env:
        - Ubuntu_Nickname=xenial16 GCC_Version=5.4.0 Regex_Supported=true  # just to make travis results easy to read
      after_success: Rscript -e 'covr::codecov()'
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - os: linux
      dist: trusty  # GCC v4.8.4
      env:
        - Ubuntu_Nickname=trusty14 GCC_Version=4.8.4 Regex_Supported=false  # just to make travis results easy to read
    - os: osx
      env: _R_CHECK_LENGTH_1_CONDITION_=true
