# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

matrix:
  include:
    - os: linux
      dist: xenial
      after_success: Rscript -e 'covr::codecov()'
      before_cache: Rscript -e 'remotes::install_cran("pkgdown")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
    - os: linux
      dist: trusty
    - os: linux
      dist: precise
    - os: osx
      env: _R_CHECK_LENGTH_1_CONDITION_=true
